# Generated by Django 4.1 on 2022-08-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_alter_studentuser_image_alter_studentuser_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
