# Generated by Django 4.1 on 2022-08-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_alter_studentuser_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
