# Generated by Django 4.1 on 2022-08-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0010_rename_procider_addscholarship_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdegree', models.CharField(max_length=100)),
                ('previousmarks', models.CharField(max_length=100)),
                ('income', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('discriotion', models.TextField()),
                ('dateaplied', models.DateField()),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.addscholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.studentuser')),
            ],
        ),
    ]
