# Generated by Django 4.1 on 2022-08-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0011_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addscholarship',
            name='scholarshipform',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
