# Generated by Django 4.1 on 2022-08-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0013_studentprofile_scholarshipform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='scholarshipform',
            new_name='addscholarshipform',
        ),
    ]
