# Generated by Django 4.1 on 2022-08-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0014_rename_scholarshipform_studentprofile_addscholarshipform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='scholarship',
        ),
    ]
