# Generated by Django 4.1 on 2022-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0015_remove_studentprofile_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='currentdegree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='discriotion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='income',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='previousmarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
