# Generated by Django 4.1 on 2022-08-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0016_studentuser_currentdegree_studentuser_discriotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarshipform', models.FileField(blank=True, upload_to='')),
                ('applyeddate', models.DateField()),
                ('addscholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.addscholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.studentuser')),
            ],
        ),
    ]
