# Generated by Django 4.1 on 2022-10-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0017_applyscholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addscholarshiptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.addscholarship')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.provider')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.studentuser')),
            ],
        ),
    ]
