# Generated by Django 4.1 on 2022-10-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0018_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='to_user',
        ),
    ]
