# Generated by Django 4.1 on 2022-10-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0019_remove_notification_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
