# Generated by Django 4.1 on 2022-10-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0021_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
