# Generated by Django 4.1 on 2022-11-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0029_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
