# Generated by Django 4.1 on 2022-11-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0030_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='user',
        ),
    ]
