# Generated by Django 4.1 on 2022-11-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0031_remove_provider_user_remove_studentuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyscholarship',
            name='addscholarship',
        ),
        migrations.RemoveField(
            model_name='applyscholarship',
            name='student',
        ),
        migrations.DeleteModel(
            name='AddScholarship',
        ),
        migrations.DeleteModel(
            name='ApplyScholarship',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
