# Generated by Django 4.1 on 2022-11-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0037_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addscholarship',
            old_name='created_at',
            new_name='time',
        ),
    ]
