# Generated by Django 4.1 on 2022-11-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0038_rename_created_at_addscholarship_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addscholarship',
            old_name='time',
            new_name='time_at',
        ),
    ]
