# Generated by Django 4.1 on 2022-12-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0045_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='total_income',
            new_name='total',
        ),
    ]
