# Generated by Django 4.1 on 2022-12-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0051_remove_studentuser_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='cnic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
