# Generated by Django 4.1 on 2022-12-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0053_studentuser_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='disability',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
