# Generated by Django 4.1 on 2022-12-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0055_studentuser_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='registration',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
