# Generated by Django 4.1 on 2022-12-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0056_studentuser_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='gcnic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='gname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='itype',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='total',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
