# Generated by Django 4.1 on 2022-12-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0059_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='end',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='start',
        ),
    ]
