# Generated by Django 4.1 on 2022-12-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0060_remove_studentuser_dob_remove_studentuser_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='hafiz',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
